AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    arm-example

Globals: 
    Api:
        EndpointConfiguration: REGIONAL
        TracingEnabled: true
    Function:
        Timeout: 5
        MemorySize: 256
        Runtime: python3.9
        Tracing: Active # 
        Environment:
            Variables:
                LOG_LEVEL: INFO
                POWERTOOLS_LOGGER_SAMPLE_RATE: 0.1
                POWERTOOLS_LOGGER_LOG_EVENT: true
                POWERTOOLS_METRICS_NAMESPACE: MyServerlessApplication
                POWERTOOLS_SERVICE_NAME: hello

Resources:
    PowerToolsLayer:
        Type: AWS::Serverless::LayerVersion
        Properties:
            ContentUri: layer
            CompatibleRuntimes:
                - python3.9
        Metadata:
            BuildMethod: makefile
    HelloWorldFunction:
        Type: AWS::Serverless::Function 
        Properties:
            Handler: app.lambda_handler
            CodeUri: hello_world
            Layers:
                - !Ref PowerToolsLayer
            Description: Hello World function
            Events:
                HelloPath:
                    Type: Api 
                    Properties:
                        Path: /hello
                        Method: GET
                HelloYou:
                    Type: Api
                    Properties:
                        Path: /hello/{name}
                        Method: GET

Outputs:
    HelloWorldApigwURL:
      Description: "API Gateway endpoint URL for Prod environment for Hello World Function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"

    HelloWorldFunction:
      Description: "Hello World Lambda Function ARN"
      Value: !GetAtt HelloWorldFunction.Arn

